title:     Jennifer Smith # your name (or website title) here
logo: "/images/Profile1Round.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  A collection of analytics projects 
  <br><br>
  Master of Science, Business Analytics
  <br>
  Drake University
  <br>
  December 2022 graduation
  <br><br>
  <a href="https://www.linkedin.com/in/jennifersmithmequon/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
